USE [master]
GO

/****** Object:  Database [SaleManagerSystem]    Script Date: 05/11/2019 02:14:06 ق.ظ ******/
CREATE DATABASE [SaleManagerSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SaleManagerSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SaleManagerSystem.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SaleManagerSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SaleManagerSystem_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SaleManagerSystem] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SaleManagerSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SaleManagerSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SaleManagerSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SaleManagerSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SaleManagerSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SaleManagerSystem] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SaleManagerSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [SaleManagerSystem] SET  MULTI_USER 
GO

ALTER DATABASE [SaleManagerSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SaleManagerSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SaleManagerSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SaleManagerSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SaleManagerSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SaleManagerSystem] SET  READ_WRITE 
GO

